# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: spf 0.0.55.pre.pre ruby lib

Gem::Specification.new do |s|
  s.name = "spf".freeze
  s.version = "0.0.55.pre.pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Andrew Flury".freeze, "Julian Mehnle".freeze, "Jacob Rideout".freeze]
  s.date = "2022-01-13"
  s.description = "    An object-oriented Ruby implementation of the Sender Policy Framework (SPF)\n    e-mail sender authentication system, fully compliant with RFC 4408.\n".freeze
  s.email = ["code@agari.com".freeze, "aflury@agari.com".freeze, "jmehnle@agari.com".freeze, "jrideout@agari.com".freeze]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "README.rdoc",
    "Rakefile",
    "lib/spf.rb",
    "lib/spf/error.rb",
    "lib/spf/eval.rb",
    "lib/spf/ext/resolv.rb",
    "lib/spf/macro_string.rb",
    "lib/spf/model.rb",
    "lib/spf/request.rb",
    "lib/spf/result.rb",
    "lib/spf/test.rb",
    "lib/spf/test/case.rb",
    "lib/spf/test/scenario.rb",
    "lib/spf/util.rb",
    "lib/spf/version.rb",
    "spec/macrostring_spec.rb",
    "spec/mech_spec.rb",
    "spec/request_spec.rb",
    "spec/resolv_programmable.rb",
    "spec/result_spec.rb",
    "spec/rfc4406-tests.yml",
    "spec/rfc4408-tests.yml",
    "spec/rfc4408_spec.rb",
    "spec/server_spec.rb",
    "spec/spec_helper.rb",
    "spec/spf_spec.rb",
    "spec/spf_test_lib.rb",
    "spec/util_spec.rb",
    "spf.gemspec"
  ]
  s.homepage = "https://github.com/agaridata/spf-ruby".freeze
  s.licenses = ["none (all rights reserved)".freeze]
  s.rubygems_version = "3.0.3".freeze
  s.summary = "Implementation of the Sender Policy Framework".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<spf>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.10"])
      s.add_development_dependency(%q<rdoc>.freeze, [">= 6.3.0"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.2"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3", ">= 2.3.9"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    else
      s.add_dependency(%q<spf>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.10"])
      s.add_dependency(%q<rdoc>.freeze, [">= 6.3.0"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.2"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3", ">= 2.3.9"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<spf>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.10"])
    s.add_dependency(%q<rdoc>.freeze, [">= 6.3.0"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.2"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3", ">= 2.3.9"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

